import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/****************************************************************
 * Run the Unix "who" command and convert the results into either a string or html.
 * The who command is typically not available on Windows machines.
 * Created by kurmasz on 1/20/15.
 ****************************************************************/
public class Who {

  /**
   * Run the {@code who} utility and return the results
   *
   * @return the set of lines generated by {@code who} as a {@code List}
   */
  public static List<String> who() {

    // place to store the output
    ArrayList<String> lines = new ArrayList<String>();

    try {
      // Launch "who" as an external process (will only run in a Unix-like environment)
      Process p = Runtime.getRuntime().exec("who");

      // Grab each line generated and place it in a List
      Scanner input = new Scanner(p.getInputStream());
      while (input.hasNext()) {
        lines.add(input.nextLine());
      }
    } catch (IOException e) {
      lines.add("There was a problem: " + e);
    } finally {
	//      input.close();
    }

    return lines;
  }


  /**
   * Generate a plain text document containing the output of {@code who}
   *
   * @return A {@code String} containing the entire document
   */
  public static String whoText() {
    StringBuffer buffer = new StringBuffer();
    buffer.append("\nCurrently logged onto the server:\n\n");

    for (String line : who()) {
      buffer.append(line);
      buffer.append("\n");
    }
    return buffer.toString();
  }

  /**
   * Generate an HTML document containing the output of {@code who}
   *
   * @return A {@code String} containing the entire document.
   */
  public static String whoHTML() {
    StringBuffer buffer = new StringBuffer();
    buffer.append("<html>\n");
    buffer.append("<head>\n");
    buffer.append("<title>Who is logged in?</title>\n");
    buffer.append("<style type=\"text/css\">\n");
    buffer.append("th, td { margin-right: 10px; padding-right: 10px;}\n");
    buffer.append("th, td { text-align: left}\n");
    buffer.append("</style>\n");
    buffer.append("</head>\n");
    buffer.append("<body>\n");
    buffer.append("<h1>Who is logged into this machine?</h1>\n");
    buffer.append("<table>\n");
    buffer.append("<tr><th>Who</th><th>Where</th><th>When</th></tr>\n");
    for (String line : who()) {
      Scanner parts = new Scanner(line);

      buffer.append("<tr><td>" + parts.next() + "</td>");
      buffer.append("<td>" + parts.next() + "</td>");
      buffer.append("<td>" + parts.nextLine() + "</td></tr>\n");
      parts.close();
    }
    
    buffer.append("</table>\n");
    buffer.append("</body>\n");
    buffer.append("</html>\n");    
    return buffer.toString();
  }


  public static void main(String[] args) {
    System.out.println(whoHTML());
  }
}
